### PR TITLE
simplified merged-block weights ui

### PR DESCRIPTION
**Pull request by wkpark**
more compact, smaller display size support

image

smaller display
image

### CODE REVIEW

**Comment by miasik** [comment]
Could you please place BASE in the middle as M00?

**Comment by hako-mikan** [comment]
I believe the position of BASE should remain as it is now. 
If you place it next to MID, it will lose its consistency with the order of weights and could lead to unnecessary confusion.

**Comment by miasik** [comment]
> If you place it next to MID, it will lose its consistency with the order of weights and could lead to unnecessary confusion.

Not on the bottom! Keep it on the top, but align in the center as M00.

**Comment by hako-mikan** [comment]
@miasik 
Ah, I misunderstood.

**Comment by wkpark** [comment]
OK. aligned like follows
image

**Pull request merged**
